/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author Ghozi
 */
import java.sql.*;
import koneksi.config;
import javax.swing.JOptionPane;
public class loginForm extends javax.swing.JFrame {
    Connection con;
    Statement stm;
    ResultSet rs;
    public static String user;
    /**
     * Creates new form loginForm
     */
    
    private void login(){
        try {
            String uname = txtUser.getText();
            String upass = txtPass.getText();
            String sql = "SELECT * FROM login WHERE user = '" + uname + "' AND pass = '" + upass + "'";
            
            con = config.Con();
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            if (txtUser.getText().isEmpty() && txtPass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap Masukkan Username dan Password");
            } else if (txtUser.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap Masukkan Username");
            } else if (txtPass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap Masukkan Password");
            } else if (rs.next()) {
                user = rs.getString("stat");
                mainForm main = new mainForm();
                JOptionPane.showMessageDialog(null, "Login Berhasil");
                main.show();
                this.setVisible(true);
                dispose();
                
            } else {
                JOptionPane.showMessageDialog(null, "Username atau Password Salah");
            }
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public static String getUser() {
        return user;
    }
    
    public loginForm() {
        initComponents();
        JButton [] btns = {btnLogin};
        for (JButton btn : btns) {
            btn.setBackground (new Color(0, 0, 102));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(102, 0, 102));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground (new Color(0, 0, 102));
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        pnlClose = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        loginIcon = new javax.swing.JLabel();
        signinText = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlRoot.setBackground(new java.awt.Color(255, 255, 51));
        pnlRoot.setLayout(null);

        pnlTitle.setBackground(new java.awt.Color(0, 0, 102));

        pnlClose.setBackground(new java.awt.Color(0, 0, 102));

        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlCloseLayout = new javax.swing.GroupLayout(pnlClose);
        pnlClose.setLayout(pnlCloseLayout);
        pnlCloseLayout.setHorizontalGroup(
            pnlCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(pnlCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );
        pnlCloseLayout.setVerticalGroup(
            pnlCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(pnlCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblClose, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addGap(0, 895, Short.MAX_VALUE)
                .addComponent(pnlClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlRoot.add(pnlTitle);
        pnlTitle.setBounds(0, 0, 925, 30);

        lblUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblUsername.setText("Username");
        pnlRoot.add(lblUsername);
        lblUsername.setBounds(370, 280, 200, 16);

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlRoot.add(txtUser);
        txtUser.setBounds(370, 300, 200, 40);

        lblPassword.setBackground(new java.awt.Color(0, 0, 0));
        lblPassword.setText("Password");
        pnlRoot.add(lblPassword);
        lblPassword.setBounds(370, 360, 200, 16);

        loginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-image-with-black-128.png"))); // NOI18N
        pnlRoot.add(loginIcon);
        loginIcon.setBounds(400, 100, 140, 120);

        signinText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signinText.setText("SIGN IN");
        pnlRoot.add(signinText);
        signinText.setBounds(430, 200, 80, 40);

        pnlLogin.setBackground(new java.awt.Color(0, 0, 0));

        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlRoot.add(pnlLogin);
        pnlLogin.setBounds(430, 440, 80, 40);
        pnlRoot.add(txtPass);
        txtPass.setBounds(370, 380, 200, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(925, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel loginIcon;
    private javax.swing.JPanel pnlClose;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JLabel signinText;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
