/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

/**
 *
 * @author Ghozi
 */
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.*;
import javax.swing.*;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;
public class siswaForm extends javax.swing.JFrame {

    Connection con;
    Statement stm;
    
    public void koneksi(){
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sekolah","root","");
        stm = con.createStatement();
        } catch(ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(null, "koneksi gagal....");
        System.out.println(e.getMessage());
        }
    }
    
    /**
     * Creates new form siswaForm
     */
    public siswaForm() {
        initComponents();
        bersih();
        tampildata();
        autoID();
        teksNisn.setEnabled(false);
        cbJKSiswa.addItem("Laki-laki");
        cbJKSiswa.addItem("Perempuan");
        cbAgamasiswa.addItem("Islam");
        cbAgamasiswa.addItem("Katolik");
        cbAgamasiswa.addItem("Protestan");
        cbAgamasiswa.addItem("Hindu");
        cbAgamasiswa.addItem("Buddha");
        cbAgamasiswa.addItem("Konghucu");
        cbJur.addItem("DKV");
        cbJur.addItem("M. Perkantoran");
        JButton [] btns = {btnInsert, btnUpdate, btnDel, btnRefresh, btnCari};
        for (JButton btn : btns) {
            btn.setBackground (new Color(0, 0, 102));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(102, 0, 102));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground (new Color(0, 0, 102));
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        pnlBack = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        pnlClose = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        pnlInput = new javax.swing.JPanel();
        lblNisn = new javax.swing.JLabel();
        teksNisn = new javax.swing.JTextField();
        lblNamasiswa = new javax.swing.JLabel();
        teksNamasiswa = new javax.swing.JTextField();
        lblJKSiswa = new javax.swing.JLabel();
        cbJKSiswa = new javax.swing.JComboBox<>();
        lblAgamasiswa = new javax.swing.JLabel();
        cbAgamasiswa = new javax.swing.JComboBox<>();
        lblNamawali = new javax.swing.JLabel();
        teksNamawali = new javax.swing.JTextField();
        lblTelpwali = new javax.swing.JLabel();
        teksTelpwali = new javax.swing.JTextField();
        lblAlamatsiswa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teksAlamatsiswa = new javax.swing.JTextArea();
        pnlButton = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        lblJur = new javax.swing.JLabel();
        cbJur = new javax.swing.JComboBox<>();
        pnlSearch = new javax.swing.JPanel();
        teksCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlRoot.setBackground(new java.awt.Color(255, 255, 51));

        pnlTitle.setBackground(new java.awt.Color(0, 0, 102));

        pnlBack.setBackground(new java.awt.Color(0, 0, 102));

        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setText("<");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlClose.setBackground(new java.awt.Color(0, 0, 102));

        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlCloseLayout = new javax.swing.GroupLayout(pnlClose);
        pnlClose.setLayout(pnlCloseLayout);
        pnlCloseLayout.setHorizontalGroup(
            pnlCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCloseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCloseLayout.setVerticalGroup(
            pnlCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCloseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Data Siswa");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addComponent(pnlBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(379, 379, 379)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlInput.setBackground(new java.awt.Color(255, 255, 51));

        lblNisn.setText("NISN");

        lblNamasiswa.setText("Nama");

        lblJKSiswa.setText("Jenis Kelamin");

        cbJKSiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        lblAgamasiswa.setText("Agama");

        cbAgamasiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        cbAgamasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgamasiswaActionPerformed(evt);
            }
        });

        lblNamawali.setText("Nama Wali");

        lblTelpwali.setText("No Telp Wali");

        teksTelpwali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teksTelpwaliKeyTyped(evt);
            }
        });

        lblAlamatsiswa.setText("Alamat");

        teksAlamatsiswa.setColumns(20);
        teksAlamatsiswa.setRows(5);
        jScrollPane1.setViewportView(teksAlamatsiswa);

        pnlButton.setBackground(new java.awt.Color(255, 255, 51));

        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Clear");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnInsert.setForeground(new java.awt.Color(255, 255, 255));
        btnInsert.setText("Save");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlButtonLayout.createSequentialGroup()
                        .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlButtonLayout.createSequentialGroup()
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblJur.setText("Jurusan");

        cbJur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        cbJur.setPreferredSize(new java.awt.Dimension(82, 22));

        javax.swing.GroupLayout pnlInputLayout = new javax.swing.GroupLayout(pnlInput);
        pnlInput.setLayout(pnlInputLayout);
        pnlInputLayout.setHorizontalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInputLayout.createSequentialGroup()
                            .addComponent(lblTelpwali, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(teksTelpwali))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInputLayout.createSequentialGroup()
                            .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAgamasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNamawali, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbAgamasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(teksNamawali)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInputLayout.createSequentialGroup()
                            .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlInputLayout.createSequentialGroup()
                                    .addComponent(lblNisn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(teksNisn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlInputLayout.createSequentialGroup()
                                    .addComponent(lblNamasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)
                                    .addComponent(teksNamasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlInputLayout.createSequentialGroup()
                                    .addComponent(lblJKSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbJKSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblAlamatsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlInputLayout.createSequentialGroup()
                                    .addComponent(lblJur, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(cbJur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlInputLayout.setVerticalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNisn)
                    .addComponent(teksNisn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamasiswa)
                    .addComponent(teksNamasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJKSiswa)
                    .addComponent(cbJKSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgamasiswa)
                    .addComponent(cbAgamasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamawali)
                    .addComponent(teksNamawali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelpwali)
                    .addComponent(teksTelpwali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlamatsiswa)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJur)
                    .addComponent(cbJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pnlSearch.setBackground(new java.awt.Color(255, 255, 51));

        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teksCari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teksCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NISN", "Nama", "Jenis Kelamin", "Agama", "Nama Wali", "No Telp Wali", "Alamat", "Jurusan"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout pnlRootLayout = new javax.swing.GroupLayout(pnlRoot);
        pnlRoot.setLayout(pnlRootLayout);
        pnlRootLayout.setHorizontalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRootLayout.createSequentialGroup()
                        .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlRootLayout.setVerticalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRootLayout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRootLayout.createSequentialGroup()
                        .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(925, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        mainForm back = new mainForm();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        if (teksNamasiswa.getText().isEmpty() && cbJKSiswa.getSelectedIndex() == 0 && cbAgamasiswa.getSelectedIndex() == 0 && teksNamawali.getText().isEmpty() && teksTelpwali.getText().isEmpty() && teksAlamatsiswa.getText().isEmpty() && cbJur.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Harap Masukkan Data Terlebih Dahulu");
        } else if (teksNamasiswa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong.");
        } else if (cbJKSiswa.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Harap Pilih Jenis Kelamin Terlebih Dahulu");
        } else if (cbAgamasiswa.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Harap Pilih Agama Terlebih Dahulu");
        } else if (teksNamawali.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Wali tidak boleh kosong.");
        } else if (teksTelpwali.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nomor Telepon tidak boleh kosong.");
        } else if (teksAlamatsiswa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Alamat tidak boleh kosong.");
        } else if (cbJur.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Harap Pilih Jurusan Terlebih Dahulu");
        } else {
            try{
                koneksi();
                String sql = "INSERT INTO siswa VALUES('"+teksNisn.getText()+"','"+teksNamasiswa.getText()+"','"+cbJKSiswa.getSelectedItem()+"','"+cbAgamasiswa.getSelectedItem()+"','"+teksNamawali.getText()+"','"+teksTelpwali.getText()+"','"+teksAlamatsiswa.getText()+"','"+cbJur.getSelectedItem()+"')";
                stm.executeUpdate(sql);
                con.close();
                tampildata();
                bersih();
                autoID();
                JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Proses penyimpanan gagal/koneksi gagal..");
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null,"NISN : "+teksNisn.getText()+" sudah ada...!!!");
                System.out.println(e.getMessage());
                bersih();
            }
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (teksNamasiswa.getText().isEmpty() && cbJKSiswa.getSelectedIndex() == 0 && cbAgamasiswa.getSelectedIndex() == 0 && teksNamawali.getText().isEmpty() && teksTelpwali.getText().isEmpty() && teksAlamatsiswa.getText().isEmpty() && cbJur.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Harap Masukkan Data Terlebih Dahulu");
        } else if (teksNamasiswa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong.");
        } else if (cbJKSiswa.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Harap Pilih Jenis Kelamin Terlebih Dahulu");
        } else if (cbAgamasiswa.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Harap Pilih Agama Terlebih Dahulu");
        } else if (teksNamawali.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Wali tidak boleh kosong.");
        } else if (teksTelpwali.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nomor Telepon tidak boleh kosong.");
        } else if (teksAlamatsiswa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Alamat tidak boleh kosong.");
        } else if (cbAgamasiswa.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Harap Pilih Jurusan Terlebih Dahulu");
        } else {
            try{
                koneksi();
                String sql= "UPDATE siswa SET nama_siswa='"+teksNamasiswa.getText()+"',"+"jk_siswa='"+cbJKSiswa.getSelectedItem()+"',"+"agama_siswa='"+cbAgamasiswa.getSelectedItem()+"',"+"nama_wali='"+teksNamawali.getText()+"',"+"telp_wali='"+teksTelpwali.getText()+"',"+"alamat_siswa='"+teksAlamatsiswa.getText()+"',"+"jurusan='"+cbJur.getSelectedItem()+"'"+"WHERE nisn='"+teksNisn.getText()+"'";

                stm.executeUpdate(sql);
                con.close();
                tampildata();
                bersih();
                autoID();
                JOptionPane.showMessageDialog(null,"Data berhasil di ubah");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Proses update gagal/koneksi gagal...");
                System.out.println(e.getMessage());
            }
            btnInsert.setEnabled(true);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        try{
            koneksi();
            String sql="delete from siswa where nisn='"+teksNisn.getText()+"'";
            stm.executeUpdate(sql);
            con.close();
            tampildata();
            bersih();
            autoID();
            JOptionPane.showMessageDialog(null,"Data berhasil di hapus");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Proses hapus gagal/koneksi gagal...");
            System.out.println(e.getMessage());

        }
        btnInsert.setEnabled(true);
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        bersih();
        autoID();
        tampildata();
        btnInsert.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int table=jTable1.getSelectedRow();
        //mengambil data dari table
        String a=jTable1.getValueAt(table,0).toString();
        String b=jTable1.getValueAt(table,1).toString();
        String c=jTable1.getValueAt(table,2).toString();
        String d=jTable1.getValueAt(table,3).toString();
        String e=jTable1.getValueAt(table,4).toString();
        String f=jTable1.getValueAt(table,5).toString();
        String g=jTable1.getValueAt(table,6).toString();
        String h=jTable1.getValueAt(table,7).toString();
       
        teksNisn.setText(a);
        teksNamasiswa.setText(b);
        cbJKSiswa.setSelectedItem(c);
        cbAgamasiswa.setSelectedItem(d);
        teksNamawali.setText(e);
        teksTelpwali.setText(f);
        teksAlamatsiswa.setText(g);
        cbJur.setSelectedItem(h);
       
        teksNamasiswa.requestFocus();
        cbJKSiswa.requestFocus();
        cbAgamasiswa.requestFocus();
        teksNamawali.requestFocus();
        teksTelpwali.requestFocus();
        teksAlamatsiswa.requestFocus();
        cbJur.requestFocus();
        btnInsert.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnDel.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String key = teksCari.getText();
        System.out.println(key);
        
        if (key!=""){
            cariData(key);
        } else {
            tampildata();
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void teksTelpwaliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksTelpwaliKeyTyped
        char e = evt.getKeyChar();
        if(!(Character.isDigit(e))){
            evt.consume();
        }
    }//GEN-LAST:event_teksTelpwaliKeyTyped

    private void cbAgamasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgamasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAgamasiswaActionPerformed
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        koneksi();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(siswaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(siswaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(siswaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(siswaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new siswaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbAgamasiswa;
    private javax.swing.JComboBox<String> cbJKSiswa;
    private javax.swing.JComboBox<String> cbJur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAgamasiswa;
    private javax.swing.JLabel lblAlamatsiswa;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblJKSiswa;
    private javax.swing.JLabel lblJur;
    private javax.swing.JLabel lblNamasiswa;
    private javax.swing.JLabel lblNamawali;
    private javax.swing.JLabel lblNisn;
    private javax.swing.JLabel lblTelpwali;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlClose;
    private javax.swing.JPanel pnlInput;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTextArea teksAlamatsiswa;
    private javax.swing.JTextField teksCari;
    private javax.swing.JTextField teksNamasiswa;
    private javax.swing.JTextField teksNamawali;
    private javax.swing.JTextField teksNisn;
    private javax.swing.JTextField teksTelpwali;
    // End of variables declaration//GEN-END:variables

    private void bersih() {
        teksNisn.setText("");
        teksNamasiswa.setText("");
        cbJKSiswa.setSelectedIndex(0);
        cbAgamasiswa.setSelectedIndex(0);
        teksNamawali.setText("");
        teksTelpwali.setText("");
        teksAlamatsiswa.setText("");
        cbJur.setSelectedIndex(0);
        teksCari.setText("");
        btnUpdate.setEnabled(false);
        btnDel.setEnabled(false);
    }
    
    private void autoID() {
        try {
            koneksi();
            String sql = "SELECT * FROM siswa ORDER BY nisn DESC";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String kode = rs.getString("nisn").substring(5);
                String up = "" + (Integer.parseInt(kode) + 1);
                String zero = "";
                if (up.length() == 1) {
                    zero = "00";
                } else if (up.length() == 2) {
                    zero = "0";
                } else if (up.length() == 3) {
                    zero = "";
                } 
                teksNisn.setText("S2023" + zero + up);
            } else {
                teksNisn.setText("S2023001");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void tampildata() {
        Object[] Baris = {"NISN", "Nama", "Jenis Kelamin", "Agama", "Nama Wali", "No. Telp", "Alamat", "Jurusan"};
        DefaultTableModel tblSiswa = new DefaultTableModel(null, Baris);
        jTable1.setModel(tblSiswa);
        String sql="SELECT * FROM siswa ORDER BY nisn ASC";

    try {
        koneksi();
        java.sql.Statement s = con.createStatement();
        ResultSet rs=s.executeQuery(sql);
        while (rs.next())   {
            tblSiswa.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
                rs.getString(8) });
        }
        jTable1.setModel(tblSiswa);
    }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Ada Kesalahan....");
        }
    }
    
    private void cariData(String key) {
        try{
            Object [] judul_kolom = {"NISN", "Nama", "Jenis Kelamin", "Agama", "Nama Wali", "No. Telp", "Alamat", "Jurusan"};
            DefaultTableModel tblSiswa = new DefaultTableModel(null,judul_kolom);
            jTable1.setModel(tblSiswa);
            
            koneksi();
            String sql="SELECT * FROM siswa WHERE nisn LIKE '%"+key+"%' OR nama_siswa LIKE '%"+key+"%' OR jk_siswa LIKE '%"+key+"%' OR agama_siswa LIKE '%"+key+"%' OR nama_wali LIKE '%"+key+"%' OR telp_wali LIKE '%"+key+"%'  OR alamat_siswa LIKE '%"+key+"%'  OR jurusan LIKE '%"+key+"%'";
            Statement stt = con.createStatement();        
            PreparedStatement pst = con.prepareStatement(sql);
            tblSiswa.getDataVector().removeAllElements();
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                Object[] data = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8)
                };
               tblSiswa.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    
}
