/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import javax.swing.JOptionPane;

/**
 *
 * @author Ghozi
 */
public class splashForm extends javax.swing.JFrame {

    /**
     * Creates new form splashForm
     */
    public splashForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lblPer = new javax.swing.JLabel();
        lblTeks = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlRoot.setBackground(new java.awt.Color(255, 255, 51));

        lblPer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPer.setText("0%");

        lblTeks.setText("Loading");

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle2.png"))); // NOI18N

        javax.swing.GroupLayout pnlRootLayout = new javax.swing.GroupLayout(pnlRoot);
        pnlRoot.setLayout(pnlRootLayout);
        pnlRootLayout.setHorizontalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlRootLayout.createSequentialGroup()
                .addGroup(pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRootLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRootLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblTeks, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRootLayout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlRootLayout.setVerticalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRootLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTeks)
                .addGap(93, 93, 93)
                .addComponent(lblPer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(250, 325));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        splashForm lp = new splashForm();
        lp.setVisible(true);
            try {
                for (int i = 0; i<= 100; i++){
                Thread.sleep(100);
                lp.lblPer.setVisible(false);
                lp.jProgressBar1.setVisible(false);
                lp.lblPer.setText(i + "%");
                if (i==10){
                    lp.lblTeks.setText("Connecting");
                }
                if (i==20){
                    lp.lblTeks.setText("Connecting .");
                }
                if (i==25){
                    lp.lblTeks.setText("Connecting . .");
                }
                if (i==30){
                    lp.lblTeks.setText("Connecting . . .");
                }
                if (i==40){
                    lp.lblTeks.setText("Connected");
                }
                if (i==50){
                    lp.lblTeks.setText("Starting");
                }
                if (i==55){
                    lp.lblTeks.setText("Starting .");
                }
                if (i==60){
                    lp.lblTeks.setText("Starting . .");
                }
                if (i==65){
                    lp.lblTeks.setText("Starting . . .");
                }
                if (i==70){
                    lp.lblTeks.setText("Starting . ");
                }
                if (i==75){
                    lp.lblTeks.setText("Starting . .");
                }
                if (i==80){
                    lp.lblTeks.setText("Starting . . .");
                }
                if (i==85){
                    lp.lblTeks.setText("Starting .");
                }
                if (i==90){
                    lp.lblTeks.setText("Starting . .");
                }
                if (i==95){
                    lp.lblTeks.setText("Starting . . .");
                }
                if (i==100){
                    loginForm log = new loginForm();
                    log.setVisible(true);
                    lp.dispose();
                }
                lp.jProgressBar1.setValue(i);
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblPer;
    private javax.swing.JLabel lblTeks;
    private javax.swing.JPanel pnlRoot;
    // End of variables declaration//GEN-END:variables
}
